import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import { Movie, MovieRouteSuccessResponseData } from '@/types';

export default function Home() {
  const [movies, setMovies] = useState<Movie[]>([]);

  useEffect(() => {
    (async () => {
      try {
        const { data } = await axios.get<MovieRouteSuccessResponseData>(
          '/api/movies',
          {
            params: { title: 'Avengers Endgame' },
          }
        );
        setMovies(data);
      } catch (error) {
        console.error(error);
      }
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Movie Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <pre>{JSON.stringify(movies, null, 2)}</pre>
      </main>
    </>
  );
}
